name: Archive Meetings

on:
  schedule:
    - cron: '30 23 * * 1-5'
  workflow_dispatch:
    inputs:
      scan_date:
        description: 'Meeting date (YYYY-MM-DD)'
        type: string
        required: false
        default: ''
      upload_and_email:
        description: 'Perform upload and email?'
        type: boolean
        required: true
        default: true
      reason:
        description: 'Reason for manual intervention'
        required: false
        default: 'Debugging the workflow'

jobs:
  archive-task:
    runs-on: ubuntu-latest
    environment: production
    env:
      OAUTH2_CREDENTIALS: ${{ secrets.OAUTH2_CREDENTIALS }}
      OAUTH2_TOKEN: ${{ secrets.OAUTH2_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      ARCHIVE_SSH_KEY: ${{ secrets.ARCHIVE_SSH_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install libwww perl packages
        run: |
          sudo apt-get install libwww-perl
        shell: bash
      - run: npm install
      - name: Copy W3C CCG configuration
        run: cp config.js node_modules/cg-archiver
      - name: Determine meeting scan date and publication preference
        run: |
          export TODAY=`TZ='America/New_York' date -I`
          export PROVIDED_SCAN_DATE=${{ inputs.scan_date }}
          export SCAN_DATE=${PROVIDED_SCAN_DATE:-$TODAY}
          echo "SCAN_DATE=$SCAN_DATE" >> $GITHUB_ENV
          echo "Scanning for meetings on $SCAN_DATE..."
          echo "Upload and email: ${{ inputs.upload_and_email }}"
      - name: Download logs and minutes
        working-directory: node_modules/cg-archiver
        run: |
          mkdir logs
          ./cg-archiver -d ${{env.SCAN_DATE}}
      - name: Send announcement, logs, and minutes to archival servers
        if: ${{ inputs.upload_and_email }}
        working-directory: node_modules/cg-archiver
        run: |
          ./cg-archiver -d ${{env.SCAN_DATE}} -u -e
