name: Archive Meetings

on:
  schedule:
    - cron: '30 23 * * 1-5'
  workflow_dispatch:
    inputs:
      scan_date:
        description: 'Meeting date (YYYY-MM-DD)'
        type: string
        required: false
        default: ''
      reason:
        description: 'Reason for manual intervention'
        required: false
        default: 'Debugging the workflow'

jobs:
  archive-task:
    runs-on: ubuntu-latest
    environment: production
    env:
      OAUTH2_CREDENTIALS: ${{ secrets.OAUTH2_CREDENTIALS }}
      OAUTH2_TOKEN: ${{ secrets.OAUTH2_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      ARCHIVE_SSH_KEY: ${{ secrets.ARCHIVE_SSH_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: perl-actions/install-with-cpm@v1
        with:
          modules: "LWP::UserAgent LWP::Protocol::https"
      - run: npm install
      - name: Copy W3C CCG configuration
        run: cp config.js node_modules/cg-archiver
      - name: Download logs and minutes
        working-directory: node_modules/cg-archiver
        run: |
          TODAY=`TZ='America/New_York' date -I`
          SCAN_DATE="${{ github.event.inputs.scan_date || TODAY }}"
          mkdir logs
          ./cg-archiver -d $SCAN_DATE
      - name: Send announcement, logs, and minutes to archival servers
        working-directory: node_modules/cg-archiver
        run: |
          TODAY=`TZ='America/New_York' date -I`
          SCAN_DATE="${{ github.event.inputs.scan_date || TODAY }}"
          ./cg-archiver -d $SCAN_DATE -u -e
